name: Release

on:
  - workflow_dispatch

env:
  BUILD_TYPE: Release
  DOTNET_VERSION: 8
  ASSEMBLY_NAME: Hosihikari.Minecraft.Foundation

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}.0.x

      - name: Build
        run: dotnet publish -c ${{ env.BUILD_TYPE }}

      - name: Publish NuGet
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/${{ env.ASSEMBLY_NAME }}.csproj
          VERSION_FILE_PATH: Directory.Build.props
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          NO_BUILD: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.ASSEMBLY_NAME }}.Publish
          path: src/bin/Release/net${{env.DOTNET_VERSION}}.0/publish/
